services:
  victorialogs:
    image: victoriametrics/victoria-logs:latest
    pull_policy: missing
    container_name: victorialogs
    restart: unless-stopped
    command: -storageDataPath=victoria-logs-data -retentionPeriod=1w
    volumes:
      - victorialogs-data:/victoria-logs-data
    x-ports:
      - 9428:9428/tcp@host
    x-machines:
      - nas

  grafana-image-renderer:
    image: grafana/grafana-image-renderer:latest
    pull_policy: missing
    container_name: grafana-image-renderer
    restart: unless-stopped
    environment:
      - GOMEMLIMIT=1GiB
    x-machines:
      - nas

  grafana:
    image: grafana/grafana:latest
    pull_policy: missing
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_NEWLOGSPANEL=false
      - GF_SERVER_ROOT_URL=https://grafana.serv4.reta.re
      - GF_RENDERING_SERVER_URL=http://grafana-image-renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_PLUGINS_PREINSTALL_SYNC=victoriametrics-logs-datasource@0.24.1@https://grafana.com/api/plugins/victoriametrics-logs-datasource/versions/0.24.1/download
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        - name: VictoriaLogs
          type: victoriametrics-logs-datasource
          access: proxy
          url: http://victorialogs:9428
          editable: false
        EOF
        /run.sh
    volumes:
      - grafana-data:/var/lib/grafana
    x-ports:
      - grafana.serv4.reta.re:3000/http
    x-machines:
      - nas

volumes:
  grafana-data:
  victorialogs-data:
