services:
  pairdrop:
    image: "lscr.io/linuxserver/pairdrop:latest"
    pull_policy: always
    container_name: pairdrop
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - WS_FALLBACK=false # Set to true to enable websocket fallback if the peer to peer WebRTC connection is not available to the client.
      - RATE_LIMIT=false # Set to true to limit clients to 1000 requests per 5 min.
      - RTC_CONFIG=false # Set to the path of a file that specifies the STUN/TURN servers.
      - DEBUG_MODE=false # Set to true to debug container and peer connections.
      - TZ=Europe/Paris # Time Zone
    x-ports:
      - drop.reta.re:3000/http # Web UI. Change the port number before the last colon e.g. `127.0.0.1:9000:3000`
    x-machines:
      - nas
