services:
  miniflux-db:
    image: postgres:14
    volumes:
      - miniflux-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
    env_file: ".env"
    environment:
      POSTGRES_USER: miniflux
      ROOT_URL: https://rss.reta.re
      POSTGRES_PASSWORD: secret
    x-machines:
      - phloeomys

  miniflux:
    image: miniflux/miniflux:2.2.16
    container_name: miniflux
    depends_on:
      miniflux-db:
        condition: service_healthy
    user: 1004:1004
    env_file: ".env"
    environment:
      RUN_MIGRATIONS: 1
      DATABASE_URL: postgres://miniflux:secret@miniflux-db/miniflux?sslmode=disable
    x-ports:
      - rss.reta.re:8080/http
    x-machines:
      - phloeomys

volumes:
  miniflux-data:
