services:
  linkding:
    image: ghcr.io/sissbruecker/linkding:latest-alpine
    pull_policy: always
    restart: unless-stopped
    user: 82:82
    environment:
      LD_CSRF_TRUSTED_ORIGINS: "https://links.astriiid.fr"
    volumes:
      - linkding-data:/etc/linkding/data
    x-ports:
      - links.astriiid.fr:9090/http
    x-machines:
      - phloeomys

volumes:
  linkding-data:
