services:
  otterwiki:
    image: redimp/otterwiki:2-slim
    pull_policy: always
    user: 1001:1001
    restart: unless-stopped
    volumes:
      - otterwiki-data:/app-data
    x-ports:
      - otterwiki.serv4.reta.re:8080/http
    x-machines:
      - phloeomys

volumes:
  otterwiki-data:
