#cloud-config

fqdn: nodes.reta.re
hostname: uncloud

# Dont update package lists and upgrade installed packages
package_update: false
package_upgrade: false

timezone: Europe/Paris

# Change root user
users:
  - name: root
    lock_passwd: false
    # Password is 'root' - change this in production!
    plain_text_passwd: root

runcmd:
  # Allow root ssh access
  - sed -i 's/#PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
  # Allow ssh access with password authentication
  - sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
  # Infect with NixOS
  - >
    curl https://raw.githubusercontent.com/elitak/nixos-infect/master/nixos-infect
    | PROVIDER="hetznercloud" NIX_CHANNEL="nixos-25.11" bash 2>&1 | tee /tmp/infect.log

write_files:
  - path: /etc/nixos/configuration.nix
    permissions: "0644"
    encoding: b64
    content: ${configuration_nix}

# Configure power management settings
power_state:
  mode: reboot
  timeout: 30
  condition: true
