services:
  librechat-api:
    container_name: LibreChat
    depends_on:
      - librechat-mongodb
      - librechat-rag-api
    image: ghcr.io/danny-avila/librechat-dev:latest
    pull_policy: always
    restart: always
    user: "1000:1000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - MONGO_URI=mongodb://librechat-mongodb:27017/LibreChat
      - MEILI_HOST=http://librechat-meilisearch:7700
      - RAG_PORT=8000
      - RAG_API_URL=http://librechat-rag-api:8000
    env_file:
      - .env
    configs:
      - source: librechat-env
        mode: 0600
        target: /app/.env
      - source: librechat-config
        mode: 0600
        target: /app/librechat.yaml
    volumes:
      - librechat-images:/app/client/public/images
      - librechat-uploads:/app/uploads
    x-ports:
      - chat.tracto.pl:8080/http
    x-machines:
      - nas

  librechat-mongodb:
    container_name: chat-mongodb
    image: mongo:8.0.17
    restart: always
    user: "999:999"
    volumes:
      - librechat-db:/data/db
    command: mongod --noauth
    x-machines:
      - nas

  librechat-meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.12.3
    restart: always
    user: "1000:1000"
    environment:
      - MEILI_HOST=http://librechat-meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - librechat-meilidata:/meili_data
    x-machines:
      - nas

  librechat-vectordb:
    container_name: vectordb
    image: pgvector/pgvector:0.8.0-pg15-trixie
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - librechat-pgdata2:/var/lib/postgresql/data
    x-machines:
      - nas

  librechat-rag-api:
    container_name: rag-api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    pull_policy: always
    environment:
      - DB_HOST=librechat-vectordb
      - RAG_PORT=8000
    restart: always
    depends_on:
      - librechat-vectordb
    env_file:
      - .env
    x-machines:
      - nas

configs:
  librechat-env:
    file: .env
  librechat-config:
    file: librechat.yaml

volumes:
  librechat-images:
  librechat-uploads:
  librechat-db:
  librechat-meilidata:
  librechat-pgdata2:
