app:
  dashboard_url: https://cloud.reta.re
  log_level: warn
  save_logs: false
domains:
  domain1:
    base_domain: v3rm.in
    cert_resolver: letsencrypt
    prefer_wildcard_cert: false
server:
  external_port: 3000
  internal_port: 3001
  next_port: 3002
  internal_hostname: pangolin
  session_cookie_name: p_session_token
  resource_access_token_param: p_token
  resource_access_token_headers:
    id: P-Access-Token-Id
    token: P-Access-Token
  resource_session_request_param: p_session_request
  secret: <random secret>
traefik:
  http_entrypoint: web
  https_entrypoint: websecure
gerbil:
  start_port: 51820
  base_endpoint: cloud.reta.re
  use_subdomain: false
  block_size: 24
  site_block_size: 30
  subnet_group: 100.89.137.0/20
rate_limits:
  global:
    window_minutes: 1
    max_requests: 100
email:
  smtp_host: host.hoster.net
  smtp_port: 587
  smtp_user: no-reply@example.com
  smtp_pass: aaaaaaaaaaaaaaaaaa
  no_reply: no-reply@example.com
users:
  server_admin:
    email: <admin email>
    password: <admin password>
flags:
  require_email_verification: true
  disable_signup_without_invite: true
  disable_user_create_org: true
  allow_raw_resources: true
  allow_base_domain_resources: true
